apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-demo
  template:
    metadata:
      labels:
        app: gateway-demo
    spec:
      containers:
        - name: gateway-demo
          image: ghcr.io/identity-com/gateway-demo:latest
          ports:
            - containerPort: 3000
